Test round
WildCodeSchool/2023-02-JS-Reims-project-2-wild-beer pull request #30
Opened 2023-04-27 15:23 UTC by JulienBenoit7

2023-04-27 15:54 UTC, rocambille commented
conflicts to resolve

2023-04-28 07:44 UTC, rocambille requested changes

2023-04-28 07:44 UTC, rocambille commented on frontend/src/components/board-components/Rounds.jsx
> +  const ChangeRound = (arr) => {
changeRound, not ChangeRound

2023-04-28 07:44 UTC, rocambille commented on frontend/src/App.css
> +
remove this empty line

2023-04-28 07:44 UTC, rocambille commented on frontend/src/components/board-components/Rounds.jsx
> +  return (
looks like a single round, so call it Round

2023-05-03 07:47 UTC, Justine-Merlin commented on frontend/src/components/board-components/Rounds.jsx
> +  return (
This is not resolved. The goal is to rename your component `Rounds` in `Round` :eyes:

2023-05-03 09:21 UTC, Justine-Merlin approved these changes

2023-05-03 09:21 UTC, merged